module.exports = {
  formHead: {
    fontSize: 30,
    color: "#fff",
    textAlign: "center",
    fontWeight: "bold",
  },
  formInput: {
    width: "80%",
    height: 40,
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 10,
    fontSize: 15,
    marginVertical: 15,
  },
  formBtnC: {
    width: "80%",
    height: 45,
    backgroundColor: "#000",
    borderRadius: 10,
    padding: 5,
    marginTop: 20,
    borderWidth: 1,
    borderColor: "#fff",
  },
  formText: {
    color: "#fff",
    textAlign: "center",
    fontSize: 25,
  },
  rightText: {
    color: "gray",
    fontSize: 15,
    textAlign: "right",
    width: "80%",
    marginVertical: 10,
  },
  centerText: {
    color: "gray",
    fontSize: 15,
  },
  formHead2: {
    fontSize: 20,
    color: "#fff",
    textAlign: "center",
  },
  formHead3: {
    fontSize: 30,
    color: "#fff",
    textAlign: "center",
    fontWeight: "bold",
    marginVertical: 20,
  },
};
